### ISSUE TITLE
Fork & upgrade to pylint 3

### ISSUE THREAD

**Issue by louisjdmartin** [omegacen/pylint-sonarjson#13]
Hi,
Our team as purposed a pull request to upgrade this plugin to pylint 3.  https://github.com/omegacen/pylint-sonarjson/pull/12 

As there is no response for this PR and the code is using LGPL Licensing, we decided to fork this project here: https://github.com/cnescatlab/pylint-sonarjson-catlab 

Do you still maintain this project ? If not, as we need it, we can continue updates with our fork and push on PIP repos (with another name).

If you have stopped developments on this projects, feel free to redirect to our fork, if you continue developments here, we will be happy to purpose other pull requests in the future :)

Have a nice week

The CNESCatLab team.

**Comment by teake** [comment]
Hi Louis, sorry for the late reply. I've indeed put this project on the back burner since I no longer work with Sonar and PyLint professionally. While I welcome a fork for continued development, I'd rather see a proper transfer of the project on GitHub and PyPI. I'll try to contact you privately for the details.
