### ISSUE TITLE
Add possibility to configure this plugin through a config file

### ISSUE THREAD

**Issue by LvffY** [omegacen/pylint-sonarjson#9]
Hi

This plugin seems to be able to solve an [very old pylint issue](https://github.com/PyCQA/pylint/issues/2293), so first : thanks for that :)

But because we can have a very large number of promoted/demoted issues, it would be very useful to be able to configure this plugin through a configuration file.

Multiple ideas here :
- Use for `pylint` configure files (like `pylintrc`)
- Use an external file (e.g. a YAML file) that would contain our configurations (and mostly our long list of promoted/demoted rules)

I don't think there is a preference for any of the two options here :)

**Comment by teake** [comment]
Hi, configuration via `pylintc` or `pyproject.toml` is already possible. I've added a section to READM.md that describes how in 3582b6c02375477605f1095ceb49856215024556.

Since you're talking a large number of issues that need to be configured, perhaps it's wiser to use `pyproject.toml`, since in TOML you can split out arrays over multiple lines.

I'm assuming this covers your needs, so I'm closing this issue. If not, feel free to reopen.
